### ISSUE TITLE
Clarity on using in uberwar

### ISSUE THREAD

**Issue by yatesco** [tolitius/mount#1]
Hi - apologies if this isn't the place for support ;-).

One pain I feel all the time with these 'state/dependency-management' libs is the conflict between dynamically defining components and producing WARs which require the ring handlers to be a simple `def`.

In Stuarts' Component I <hack>simply have the handler pull the components it needs directly out of the `#'system`</hack>.

Is there a more elegant answer with mount?

Specifically, what would a web UI look like on top of your demo app which exposes the nyse-finder via a HTTP endpoint.  Is it really just a simple as ring's `:init` method pointing to something which calls `(mount/start)` and the handlers then just `require` the `nyse` namespace?

Thanks!

**Comment by tolitius** [comment]
@yatesco, I won't give you _the_ anwer, I'll give _an_ answer :) Because there are many ways you can start a web app. For example one of the projects I use mount for does not use ring at all, but a netty web server.

I am sure we can arrive to _the_ answer you are looking for together, and I hope as people start using mount, we'll collect more examples. But here is what I think:
- The app needs to be reloadable (should not block on a particular state)
- The uberjar/war needs an entry point that does not block

Here is an [example](https://github.com/tolitius/mount/blob/master/doc/uberjar.md#creating-reloadable-uberjarable-app) you can try.

It does not use `:ring :init`, but I believe nothing is stopping it to. If you change this example app, and let me know your desired configuration, I'll definitely document it as an alternative, as others may find it helpful.

**Comment by yatesco** [comment]
Thanks @tolitius - I will have a look later.

I mention `ring` specifically as `ring uberwar` introduces the restriction of no-arg `handlers`.

**Comment by tolitius** [comment]
@yatesco someone else asked me about ":ring :handler/:init" on #mount clojurians slack channel, hence I created an example so there is no confusion. It lives in a [lein-ring](https://github.com/tolitius/mount/tree/lein-ring) branch. 

In short, you were right, you can just put `mount.core/start` on `:init`, or have `(mount.core/start)` within the handler. Here is a [working example](https://github.com/tolitius/mount/blob/lein-ring/project.clj#L33) from the app:

``` clojure
:ring {:handler app.www/mount-example-routes
       :init mount.core/start
       :port 4242}
```

Which works with [regular routes](https://github.com/tolitius/mount/blob/lein-ring/dev/clj/app/www.clj#L7), as you would expect. Let me know if that helps.

**Comment by tolitius** [comment]
added a [packaging](https://github.com/tolitius/mount/blob/master/README.md#packaging) section to the docs.

**Comment by tolitius** [comment]
I am going to close it, but feel free to reopen if you have any additional questions

**Comment by yatesco** [comment]
Thanks Anatoly - not much bandwidth at the moment.
