### ISSUE TITLE
Any thoughts on ClojureScript version?

### ISSUE THREAD

**Issue by edvorg** [tolitius/mount#10]
It will be very consistent to manage application state the same way for Clojure and ClojureScript, isn't it?

**Comment by tolitius** [comment]
@edvorg, sounds very logical. 

It would be good to hear from more people on how they manage state in ClojureScript apps, since I think the story there is a bit different: 
- we have react wrappers that manage _some_ state (and do it differently :))
- we have browser's localStorage / [datascript](https://github.com/tonsky/datascript)
- `reloadability` concept is a bit different there since the runtime is no longer JVM
- ClojureScript on ClojureScript / [Bootstrapping the Compiler](https://github.com/clojure/clojurescript/wiki/Bootstrapping-the-Compiler)
- and we have [figwheel](https://github.com/bhauman/lein-figwheel) :)

It is possible that help there is needed as well. While I clearly see the real benefit from mount in the Clojure JVM world, at this point I don't know enough to understand whether something like mount is needed in the ClojureScript world.

**Comment by domkm** [comment]
I use Stuart Sierra's Component for state management in both Clojure and ClojureScript. I would consider using Mount of it supported ClojureScript.

**Comment by tolitius** [comment]
@DomKM great, thanks for your feedback!

I talked to several developers already, and it seems that the consensus is "yay" :)

Could you share what specifically would be useful to use mount for in the ClojureScript universe? One obvious candidate is a websocket connection, but it would be good to collect more ideas, so we better understand the landscape.

**Comment by edvorg** [comment]
We could also wrap application state atoms in mount state. Timbre initialization, some security stuff setup. Another potential usage is browser side databases - we need to initialize and store connection.

**Comment by domkm** [comment]
A browser has many stateful singletons (`localStorage`, `history`, etc.). Managing these with start and stop procedures is important but many ClojureScript developers don't use Component for these because: a. reloading a whole page is fast in comparison to restarting a JVM process
b. Component is not well-suited for singletons

Off the top of my head, here are some browser-side stateful components I've used:
- `localStorage` wrapper that serializes/deserializes EDN
- `history` wrapper for routing
- React wrapper for one or sometimes multiple roots
- `document.title` wrapper that listens to routes
- web socket wrapper (technically, I just wrap Sente)
- DataScript (or app state atom)

I use Component because it allows me to reset the system automatically using figwheel or boot-reload. However, I think Mount would probably be better for browser ClojureScript because it embraces stateful singletons.

I would suggest not looking at ClojureScript as some foreign environment with vastly different needs than Clojure. Much of the value in libraries that are compatible with both Clojure and ClojureScript is that they provide consistent behavior and APIs so code can be shared. So, while server and browser environments are inherently different, Mount would provide the most value if the Clojure and ClojureScript versions were identical. In other words, a direct port to ClojureScript would be more useful than something specific to ClojureScript with a different API.

**Comment by tolitius** [comment]
@edvorg, @DomKM thank you.

yes, I am only thinking about a direct port ([`.cljc`](http://clojure.org/reader#The%20Reader--Reader%20Conditionals)) that would allow transparent usage regardless the environment. The examples you both gave are also very useful for testing and cljs mount examples.

**Comment by tolitius** [comment]
it seems that a runtime namespace support, the way it is done in Clojure (i.e. `ns-interns`, `ns-xyz`, etc.) is not available in ClojureScript. moreover, all bets are off, and relying on namespaces is not a way to go, in case of an `:advanced` compilation `cljs` mode.

there is a way to move forward with [bootstrap](https://github.com/swannodette/cljs-bootstrap) to `eval` namespace cljs marcos at runtime, i.e.:

``` clojure
(cljs/eval-str (cljs/empty-state) 
               "(ns-interns 'cljs.user)" 
               "ns-interns" 
               {:eval cljs/js-eval} 
               identity)
```

but would also _not_ work in `:advanced` mode.

I need ideas :)

**Comment by domkm** [comment]
@tolitius Does [`cljs.analyzer.api`](https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/analyzer/api.clj) provide what you need?

**Comment by tolitius** [comment]
@DomKM that is where I started, but it uses `env/*compiler*` which is not available at runtime (browser) i.e. [ns-interns](https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/analyzer/api.clj#L173).

that's why [bootstrap cljs](https://github.com/swannodette/cljs-bootstrap) was the next idea.

**Comment by domkm** [comment]
I would suggest that bootstrapped CLJS is not a worthwhile approach. It's unlikely to be used for web development since it is large and slow (compared the JVM-compiled CLJS).

I'm not really familiar with the implementation of Mount so could you explain why it is necessary to have access to `ns-` functions at runtime instead of compile time?

**Comment by tolitius** [comment]
@DomKM: sure.

States are created in various namespaces that developers choose to create them in. Mount scans namespaces to find them all to later do start/stop/suspend/resume. It also has a way to build dependency/status graphs, but those are not critical, just a visual. 

States are "Var"s, so whenever their state is changed via a particular lifecycle fn, the Var gets `intern`ed to the new state.

However, your simple question is **great**! Later in mount dev time (a week it was written), I added some internal state, where I keep orders for particular states. The order is revealed by Clojure (and hopefully soon ClojureScript) compiler, since it walks all the vars in order. Mount just records that order.

Most likely this internal state can be reused to `find-all-states` that mount needs, rather then diving into namespaces. I would still need `ns-resolve` and `*ns*` to _record_ namespaces, `intern`(it's not in `cljs` so an alternate solution) and optionally `ns-refers` to find ns dependencies, but just thinking outside of namespaces may get me past `ns-interns` [problem](https://gist.github.com/tolitius/c17b2d4a98eabb591926).

**Comment by tolitius** [comment]
from the example cljs [mini app](https://github.com/tolitius/mount/tree/cljc/test/mount/example):

`:advanced` mode (`$ lein do clean, cljsbuild once prod`) results:

![image](https://cloud.githubusercontent.com/assets/136575/11639456/044879ec-9cfb-11e5-9712-30c4f95f63a2.png)

let me know what you guys think.

**Comment by tolitius** [comment]
cljs is now supported in [0.1.6](https://clojars.org/mount/versions/0.1.6) > [managing-state-in-clojurescript](https://github.com/tolitius/mount/blob/master/doc/clojurescript.md#managing-state-in-clojurescript)

**Comment by domkm** [comment]
Very nicely done. Thanks, @tolitius!

**Comment by edvorg** [comment]
Much appreciated!

**Comment by arichiardi** [comment]
:+1:
