### ISSUE TITLE
defstate not resolvable by Cursive in 0.1.13+

### ISSUE THREAD

**Issue by cap10morgan** [tolitius/mount#102]
It looks like wrapping the `defstate` macro in `deftime` has rendered it unresolvable to Cursive in mount 0.1.13+. Normally you can tell Cursive's static analysis tooling "treat this symbol like `def`" and if applied to something like mount's `defstate`, it will then understand that `defstate foo` defines a new symbol `foo` that other code can refer to. But that doesn't work for `defstate` anymore and seems related to this `deftime` wrapping.

**Comment by tolitius** [comment]
hm.. I am a `vi` user, so not sure about Cursive. @arichiardi do you have an idea?

**Comment by arichiardi** [comment]
I am an Emacs user but I have Cursive colleagues. 

Nobody has complained as Cursive is usually having hard time with macros. Having said that I would ask directly @cursive-ide :smile:

In theory achieving support for ClojureScript self-host could be achievable without macrovich or those macros but it got introduced because a "very quick win".

**Comment by cursive-ghost** [comment]
Actually, I just added support for macrovich in cursive-ide/cursive#1847, so this should hopefully be resolved in the next Cursive EAP.

**Comment by mitchelkuijpers** [comment]
I can confirm it works in the current Cursive, so I think we can close this issue.

**Comment by cap10morgan** [comment]
Yep, thanks for following up!
