### ISSUE TITLE
Please add config for clj-kondo to understand defstate

### ISSUE THREAD

**Issue by holyjak** [tolitius/mount#128]
Hello! Clj-kondo is more and more popular, and e.g. VS Code + Calva use it by default. As is, it will complain about any `defstate <name>` that the name is an unknown symbol. It is as simple to fix as

```clj
;; clj-kondo config.edn
{:lint-as {mount.core/defstate clojure.core/def}}
```

however it would be much nicer if Mount came with the config so that it can be added to kondo automatically (in the case of Calva) or simply manually with kondo's [config import](https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#exporting-and-importing-configuration).

It is as simple as providing `src/clj-kondo.exports/mount/mount/config.edn` with that configuration.

**Comment by rajcspsg** [comment]
The emacs-lsp is also giving error like [this](https://imgur.com/a/iB2OhIB)

**Comment by zain83986667** [comment]
To help clj-kondo understand defstate in your Clojure code, you can add the following configuration to your deps.edn file:

ruby
Copy code
{:aliases
 {:lint
  {:extra-deps
   {vlaaad/clj-kondo {:mvn/version "RELEASE"}}
   :main-opts ["-c" "clj-kondo.config/your-config.edn"]}}}
And in your your-config.edn file, you can add the following:

ruby
Copy code
{:lint-as {:defstate :special-form}
 :vars {:defstate {:lint-as :dynamic-var}}}
This configuration tells clj-kondo to recognize defstate as a[ special](https://gskyertelescope.net/gskyer-telescope-az50350-review/) form instead of a regular function, and also to lint it as a dynamic variable instead of a regular variable.

Note that you may need to adjust the configuration to match your specific use case, and that this configuration assumes you are using clj-kondo version RELEASE.

**Comment by imrekoszo** [comment]
This last comment appears to be made by a bot.

**Comment by Samy-33** [comment]
Maybe one of us could raise a PR for this feature? I have no idea how to do that. Will be back when I get more info.

**Comment by Sleepful** [comment]
+1 I am getting a diagnostic from my LSP that says: 
```clj
(defstate xt-node
  :start (start-xtdb!)
  :stop (.close xt-node))

Unresolved symbol: xt-node
```

**Comment by zalab547** [comment]
Swift Blood Tests Walk-In Blood Tests understands the need to offer a convenient and a hassle-free solution for individuals requiring blood tests in Basildon, Billericay ,[Thurrock](https://swiftbloodtests.co.uk/the-convenient-alternative-to-walk-in-blood/), Orsett, Brentwood, Rayleigh, Southend, Wickford and surrounding areas. With our home blood testing service, you can skip the inconvenience of walk-in appointments, long waits, and parking troubles at hospitals. We will explore the benefits of our service and why it is a convenient alternative for those in need of blood tests in these areas.

**Comment by boomlyrical** [comment]
1. Create or update `.clj-kondo/config.edn` in your project.
2. Add the following to recognize `defstate[`:](https://onegpl.com/)

```edn
{:macros ['your-ns/defstate']}
``[`](https://onegpl.com/)

3. Save and re-run `clj-kondo`[.](https://onegpl.com/%d8%a3%d9%81%d8%b6%d9%84-%d8%b7%d8%b1%d9%82-%d8%aa%d8%b3%d8%af%d9%8a%d8%af-%d9%82%d8%b1%d9%88%d8%b6-%d8%a7%d9%84%d8%b9%d8%b3%d9%83%d8%b1%d9%8a%d9%8a%d9%86-%d8%a8%d8%b3%d8%b1%d8%b9%d8%a9-%d9%88%d8%a3/)

**Comment by julienba** [comment]
> 1. Create or update `.clj-kondo/config.edn` in your project.
> 2. Add the following to recognize `defstate[`:](https://onegpl.com/)

Is that a new kind of spam? :sweat_smile:

**Comment by tolitius** [comment]
yea :(
looks like it:
<img width="336" alt="image" src="https://github.com/user-attachments/assets/99f9f204-6916-425c-be5e-e814eda40230" />
