### ISSUE TITLE
Load/execution order not clear

### ISSUE THREAD

**Issue by mowat27** [tolitius/mount#13]
Hi,

I'm not sure if I'm missing the point here, but I'm having trouble with things not being started at the point when I need them.  For example, when I have 2 files...

``` clojure
(ns oddity.core
  (:require [mount :refer (defstate)]))

(println "Loading core")
(defn open-a-thing []
  "hello world")
(defstate thing
  :start (open-a-thing))
```

and

``` clojure
(ns oddity.thing-user
  (:require [oddity.core :refer (thing)]))

(println "Opening thing_user")
(println thing)
```

Then I get the following

```
user> (dev)
#object[clojure.lang.Namespace 0x2ce92a78 "dev"]
dev> go
#object[dev$go 0x50c9780d "dev$go@50c9780d"]
dev> (go)
:ready
dev> (reset)
:reloading (oddity.core oddity.thing-user oddity.core-test dev)
#object[mount.NotStartedState 0x1d2642c9 'thing' is not started (to start all the states call mount/start)]
:ready
```

Here's my project

``` clojure
(defproject oddity "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [mount "0.1.2"]]
  :profiles {:dev {:dependencies [[org.clojure/tools.namespace "0.2.11"]]
                   :source-paths ["dev"]}})
```

My dev/dev.clj is a modified version of the nyse example

``` clojure
(ns dev
  "Tools for interactive development with the REPL. This file should
  not be included in a production build of the application."
  ;; (:use [cljs.repl :only [repl]]
  ;;       [cljs.repl.browser :only [repl-env]])
  (:require [clojure.java.io :as io]
            [clojure.java.javadoc :refer [javadoc]]
            [clojure.pprint :refer [pprint]]
            [clojure.reflect :refer [reflect]]
            [clojure.repl :refer [apropos dir doc find-doc pst source]]
            [clojure.set :as set]
            [clojure.string :as str]
            [clojure.test :as test]
            ;; [clojure.core.async :refer [>!! <!! >! <! go-loop alt! timeout]]
            [clojure.tools.namespace.repl :as tn]
            [mount]))

(defn start []
  (mount/start))

(defn stop []
  (mount/stop))

(defn refresh []
  (stop)
  (tn/refresh))

(defn refresh-all []
  (stop)
  (tn/refresh-all))

(defn go
  "starts all states defined by defstate"
  []
  (start)
  :ready)

(defn reset
  "stops all states defined by defstate, reloads modified source files, and restarts the states"
  []
  (stop)
  (tn/refresh :after 'dev/go))
```

and dev/user.clj

``` clojure
(defn dev
  []
  (require 'dev)
  (in-ns 'dev))
```

**Comment by tolitius** [comment]
does your `oddity.core` reside under `src`?

the reason I ask is because I only see `:source-paths ["dev"]`. does `oddity.core` live there as well?

**Comment by mowat27** [comment]
Hi,

Yes, it's at `src/oddity/core.clj`

My project.clj now looks like this but I still have the same error

``` clojure
(defproject oddity "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [mount "0.1.2"]]
  :profiles {:dev {:dependencies [[org.clojure/tools.namespace "0.2.11"]]
                   :source-paths ["dev" "src"]}})
```

**Comment by mowat27** [comment]
I just pushed the full project to https://github.com/mowat27/oddity

**Comment by tolitius** [comment]
ok, great. makes it a lot easier to see what's going on.

here is what I currently see:

``` clojure
[oddity]$ lein repl                                                                                             (master ✔)
user=> (dev)(reset)

#object[clojure.lang.Namespace 0x2ba22f52 "dev"]
:reloading (oddity.core oddity.thing-user oddity.core-test dev)
Loading core
Opening thing_user
#object[mount.NotStartedState 0x61766f2d 'thing' is not started (to start all the states call mount/start)]
14:27:14.789 [nREPL-worker-0] INFO  mount - >> starting..  thing
:ready

;; subsequent resets will work
dev=> (reset)
14:27:20.449 [nREPL-worker-0] INFO  mount - << stopping..  thing
:reloading ()
14:27:20.471 [nREPL-worker-0] INFO  mount - >> starting..  thing
:ready
dev=>
```

the culprit on the _very first_ run is a global reference that you have [here](https://github.com/mowat27/oddity/blob/master/src/oddity/thing_user.clj#L6):

``` clojure
(ns oddity.thing-user
  (:require [oddity.core :refer (thing)]))

(println "Opening thing_user")

(println thing)  ;; <<< tools.namespace will execute it on (refresh)
```

since in oddity's `dev.clj` a tools.name/refresh [comes](https://github.com/mowat27/oddity/blob/master/dev/dev.clj#L42) _before_ (mount/start), the `thing` has not been started yet.

all _subsequent_ calls to `(reset)` as you see above, have no problems, since mount is in the loop at this point.

---

two takeaways from this: 
- while they would still work depending on `dev.clj` sequence of actions, global references are bad :)
- this deserves a better documentation on my part

let me know if this helps, and whether you must have _global_ references to states prior to the first system restart.

**Comment by mowat27** [comment]
Hi,

Sorry for the delay in replying. Last week was a busy week!

> > while they would still work depending on dev.clj sequence of actions, global references are bad :)

I was working on the basis that my `thing` would be constructed based on a config file like in your nyse example.  

I can see the problem in my thinking though.  We can only reference state defined by `defstate` inside functions rather than then top-level namespace.

This works

``` clojure
(defn use-thing [s]
  (str thing " " s))
```

... but this only works if `mount/start` has been called before the namespace has been loaded.

``` clojure
(def use-again (partial str " " thing))
```

... and that's not guaranteed when we're using the reloaded workflow - especially on initial startup and `refresh-all`.  This is confusing because the semantics of `thing` are different depending on whether it is defined using `def` or `defstate`.

So, as I said - it was user error on my part :-)

But having said that, I can't help but feel clojure naturally pulls you down the route of global shared state and mount seems to embrace that way of thinking and I like the batteries-included feel.  I'd really like a way to write normal clojure and have mount worry about managing the global state.  I can't see an easy solution but I'll ponder on it.

One question - is there an easy way to check whether mount has been started?

Cheers

Adrian

**Comment by tolitius** [comment]
Adrian,

  Thanks for your feedback. Here is where I think the confusion is coming from: `reloaded workflow`.

  I believe `reloaded workflow` suffers from the same problem that `Component` does: it takes Clojure away from you. Including defs: [No Global State](https://github.com/clojure/tools.namespace#no-global-state).

  mount is _not_ based on or needs `reloaded workflow`, and all the examples are there so it is easier to follow for developers  that are used to it.

  I am not saying that `reloaded workflow` is bad, I currently use it for one of the larger projects myself, but then I have another project where I just use mount without `reloaded workflow`, which works just as good.

---

  I need a clarification on:

``` clojure
(defn use-thing [s]
  (str thing " " s))
```

> ... but this only works if mount/start has been called before the namespace has been loaded.

The way you would use this `thing` state in the `use-thing` function would be to `:require` it in the namespace where `use-thing` lives. `:require`ing the `thing` would make it available (not started).

In order to _use_ the `use-thing` function, a `(mount/start)` will need to be called, otherwise the `thing` is a `NotStartedState`, which is one of the mount types to indicate that this state has not been started yet.

**Comment by tolitius** [comment]
> is there an easy way to check whether mount has been started?

since you can [start states selectively](https://github.com/tolitius/mount#start-and-stop-parts-of-application), you would be best to decide which states you need to be started at any particular moment to consider your "app to be started".

mount has `(states-with-deps)` function that allows you to see the state of the whole application:

``` clojure
dev=> (states-with-deps)

({:name app-config, :order 1, 
                    :started? true
                    :suspended? false
                    :ns #object[clojure.lang.Namespace 0x6e126efc "app.config"], 
                    :deps ()} 

 {:name conn, :order 2, 
              :started? true
              :suspended? false
              :ns #object[clojure.lang.Namespace 0xf1a66a6 "app.nyse"], 
              :deps ([app-config #'app.config/app-config])} 

 {:name nrepl, :order 3, 
               :started? true
               :suspended? false
               :ns #object[clojure.lang.Namespace 0x2c134117 "app"], 
               :deps ([app-config #'app.config/app-config])})
```

I mean to use it to create a selfupdating visual state of an application, but you can definitely use it for other things. I would be very interested to know what they are though :)

**Comment by mowat27** [comment]
Hi,

Thanks.  That makes sense.  

> > I believe reloaded workflow suffers from the same problem that Component does: it takes Clojure away from you. 

Yup, I'm beginning to realise that now!  I find I miss it when I don't have it though.

> > [No Global State](https://github.com/clojure/tools.namespace#no-global-state)

Ha - yup, it was right there now I look again

I said....

> > ... but this only works if mount/start has been called before the namespace has been loaded.

That comment was unclear. I meant that the next example (using a partial) depended in the namespace being loaded.  The first example (using a function) would work as you said.

Adrian

**Comment by mowat27** [comment]
Thanks for the info on how to what has been started.  TBH, I'm not sure where I'm going with it but it's good to know

**Comment by mowat27** [comment]
I'm happy to close this off now.

**Comment by tolitius** [comment]
sure. let me know if you have any follow up questions / suggestions.

---

interesting point about `partial`. I understand why intuitively, you would expect the `thing` to change after `(mount/start)`, but the way `partial` works, it copies the value (i.e. pass by value) and reuses it on every call from its original lexical scope.

Here is an example with pretending a `thing` is an atom:

``` clojure
dev=> (def thing (atom 42))
#'dev/thing

dev=> (def use-thing (partial str " " @thing))
#'dev/use-thing

dev=> (use-thing)
" 42"

dev=> (swap! thing inc)
43

dev=> @thing
43

dev=> (use-thing)
" 42"
dev=>
```

to get its argument `partial` will only dereference this atom once, and won't be looking for more changes. Same thing happens with using a `partial` with mount's "not started" state.
