### ISSUE TITLE
Mount stops state on evaluation

### ISSUE THREAD

**Issue by malchmih** [tolitius/mount#22]
When I evaluate (in CIDER, for example) running state, mount calls it's `stop` function. I believe it is connected to #18

**Comment by tolitius** [comment]
@malchmih right, since the reference to the state is wiped out, it stops (i.e. cleans) the state on recompilation / refresh.

**Comment by malchmih** [comment]
Yeah, I see. Actually, the issue is slightly different. Let's say, you have such a state:

``` clojure
(defstate some-state
  :start ((fn [] {:key some-value}))
  :stop (some-cleanup-fn))
```

Where `some-cleanup-fn` might return `nil`. Then after several evaluations you can get `NullPointerException`. Which is very misleading - you don't expect that from `def...` macro. Exactly this happened to me. What do you think?

**Comment by tolitius** [comment]
interesting. 
- can you elaborate on `after several evaluations you can get NullPointerException`?
- which version of `mount` are you using? can you try `0.1.6`?

when mount [cleans up](https://github.com/tolitius/mount/blob/master/src/mount/core.cljc#L137) that state it [redefs](https://github.com/tolitius/mount/blob/master/src/mount/core.cljc#L145) the var to be (starting from `0.1.6`) a [DerefableState](https://github.com/tolitius/mount/blob/master/src/mount/core.cljc#L118).

Since you just recompiled, but have not called a start on it, it will be in a NonStartedState (at least it should):  not `nil`. It might be that since you are using pre `0.1.6`, the [defonce](https://github.com/tolitius/mount/blob/0.1.5/src/mount/core.clj#L65) would not _re_define a var, and the state would end up to be the return value of the `stop` function.

Can you confirm you see the same behavior with `0.1.6`?

**Comment by malchmih** [comment]
This is how it looks like:

``` clojure
user> (dev)
#namespace[dev]
dev> (reset)
:reloading (...)
start
:ready
stop
stop
stop
stop
stop
stop
stop
stop
stop
dev> 
```

with a state as simple as:

``` clojure
(defstate game-service
  :start (println "start")
  :stop (println "stop"))
```

I called `reset` once, which started whole system. Then evaluated `defstate` form several times.

**Comment by malchmih** [comment]
And yes, version is correct `[mount "0.1.6"]`

**Comment by tolitius** [comment]
@malchmih, yes I believe I [see it](https://github.com/tolitius/mount/blob/0.1.7/src/mount/core.cljc#L54). Can you try [0.1.7-SNAPSHOT](https://clojars.org/mount/versions/0.1.7-SNAPSHOT) see if it fixes it?

**Comment by malchmih** [comment]
Yes, the issue is fixed, thank you! Also I think it's worth mentioning in the documentation, that evaluation stops the state.

**Comment by tolitius** [comment]
yep, thanks for the feedback. I'll leave it open, until I update the docs.

**Comment by tolitius** [comment]
should now also notify when it cleans abandoned states:

![image](https://cloud.githubusercontent.com/assets/136575/11818203/04d8049a-a327-11e5-9d02-f7a28ad169d4.png)

**Comment by malchmih** [comment]
Great, thanks for your work!

**Comment by tolitius** [comment]
sure, thanks for reporting this!
here is the note about ns recompilation: https://github.com/tolitius/mount#recompiling-namespaces-with-running-states

**Comment by tolitius** [comment]
now (`0.1.8-SNAPSHOT`) it would just restart affected states on ns reload: https://github.com/tolitius/mount/blob/0.1.8/README.md#recompiling-namespaces-with-running-states

**Comment by malchmih** [comment]
Great, even better :blush:
