### ISSUE TITLE
suspend and resume vars still in logging

### ISSUE THREAD

**Issue by freakhill** [tolitius/mount#53]
:suspend and :resume were removed but are still present in mount/dev/clj/app/utils/logging.clj

**Comment by tolitius** [comment]
`mount/dev/clj/app/utils/logging.clj` isn't really a part of mount, but you're right, it should have been fixed with the `0.1.10` example.

it [was updated](https://github.com/tolitius/mount/commit/78b9a23c713778807e301204e7c1db44953d6609) some time ago, so if you pull master, you should get an [updated version](https://github.com/tolitius/mount/blob/master/dev/clj/app/utils/logging.clj) of the example app.

let me know if it helps.

**Comment by freakhill** [comment]
I quickly patched it by hand thanks! I will copy paste your version later!

**Comment by tolitius** [comment]
sure, let me know if it works for you once you get to `copy/paste`
