### ISSUE TITLE
def doesn't work with mount

### ISSUE THREAD

**Issue by kwladyka** [tolitius/mount#77]
```clojure
(mount/defstate foo
                :start (println "!!! start")
                :stop (println "!!! stop"))

(def app foo)

(mount/start)
```

Then `app` throw an error `mount.core.DerefableState cannot be cast to clojure.lang.IFn`. This is typical situation when you use `ring` and have `app` and `routes` definition. This is how i get this situation.

It tooks me some time to discover it. If you can't fix it it will be nice to add information about it in the readme.

**Comment by tolitius** [comment]
Could you give a more specific example with ring, app and routes?

check out:

* the [Packaging](https://github.com/tolitius/mount#packaging) section in the docs
* [these](https://github.com/tolitius/stater#stater) sample web apps
* an [example](https://github.com/tolitius/mount/blob/lein-ring/project.clj#L33-L35) with ring `:init` hook

All of the above based on ring. Let me know if this helps.

**Comment by kwladyka** [comment]
```clojure
(def app
  (-> handler
      wrap-keyword-params
      wrap-nested-params
      wrap-params
      wrap-restful-format))
```

Like about situation above.

`def` is set before `(mount/start)` so `app` has value with not started state `handler`. This value doesn't change after `(mount/start)`. This is to solve by just adding `app` by `defstate` but first somebody have to know `mount` doesn't work with `def`.

**Comment by tolitius** [comment]
I am not sure why do you need to use `def` in this situation, since it will be evaluated every time this namespace is required / evaled in REPL / etc.

Why can't you do something like:

```clojure
(defroutes app-routes

  (GET "/" [] "welcome to smsio!")

  (POST "/sms/:from/:to/:msg" [from to msg]
    (generate-string
      @(send-sms {:from from
                  :to to
                  :body msg}))))

(defn start-www [{:keys [www]}]
  (-> (routes app-routes)
      (handler/site)
      (run-jetty {:join? false
                  :port (:port www)})))

(defstate web-server :start (start-www config)
                     :stop (.stop web-server))  ;; it's a "org.eclipse.jetty.server.Server" at this point
```

you can follow the above example app [here](https://github.com/tolitius/stater/blob/master/smsio/src/app/www.clj#L10-L24).

**Comment by kwladyka** [comment]
I can. As i wrote:

> This is to solve by just adding `app` by `defstate` but first somebody have to know `mount` doesn't work with `def`.

So suggestion of this issue is to fix it for `def` or write in the readme it doesn't work with `def`.

**Comment by tolitius** [comment]
I just don't think
> it doesn't work with `def`

is accurate. here is why:

mount has two modes `clj` and `cljc`. Here is [more details](https://github.com/tolitius/mount/blob/master/doc/clojurescript.md#managing-state-in-clojurescript) of why this is the case.

In `clj` mode, a state is a managed Clojure var. When `(mount/start)` is called, it changes the value of the state to its "started" value. If you previously had _another_ var linked to it, this other var (i.e. `app`) would not change, since it is not managed, and this is how Clojure vars work in general. Once you `def` something it stays the same.

In `cljc` mode your example would work as you would expect it:

```clojure
boot.user=> (require '[mount.core :as mount :refer [defstate]])
nil
boot.user=> (mount/in-cljc-mode)
:cljc
```
```clojure
boot.user=> (mount/defstate foo :start 42)
#'boot.user/foo
boot.user=> (def app foo)
#'boot.user/app
boot.user=>
```
```clojure
boot.user=> (mount/start)
{:started ["#'boot.user/foo"]}
boot.user=>

boot.user=> foo
#object[mount.core.DerefableState 0x1ff8da72 {:status :ready, :val 42}]
boot.user=> app
#object[mount.core.DerefableState 0x1ff8da72 {:status :ready, :val 42}]
boot.user=>

boot.user=> @foo
42
boot.user=> @app
42
```

**Comment by kwladyka** [comment]
Thanks to explain it to me. So i can only suggest to add short info about this difference between normal mode and cljs mode in readme. But not in ClojureScript section only. Or maybe only i spent a little time to discover this :)

**Comment by kwladyka** [comment]
not active
